export type ModelPreset = {
  provider: string;
  name: string;
  display_name: string;
  description: string;
  model: string;
  api_base: string;
  supports_vision: boolean;
  supports_thinking: boolean;
  supports_reasoning_effort: boolean;
  use_responses_api: boolean;
  output_version: string | null;
  thinking: Record<string, unknown> | null;
  when_thinking_enabled: Record<string, unknown> | null;
};

export const modelPresets: ModelPreset[] = [
  {
    provider: "OpenAI",
    name: "openai-gpt-4o",
    display_name: "GPT-4o",
    description: "OpenAI GPT-4o - 多模态旗舰模型，支持视觉和思考",
    model: "gpt-4o",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-gpt-4o-mini",
    display_name: "GPT-4o Mini",
    description: "OpenAI GPT-4o Mini - 高性价比多模态模型",
    model: "gpt-4o-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-o3",
    display_name: "OpenAI o3",
    description: "OpenAI o3 - 下一代推理模型",
    model: "o3",
    api_base: "https://api.openai.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Anthropic",
    name: "anthropic-claude-3-5-sonnet",
    display_name: "Claude 3.5 Sonnet",
    description: "Anthropic Claude 3.5 Sonnet - 智能与速度平衡",
    model: "claude-3-5-sonnet-20241022",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Anthropic",
    name: "anthropic-claude-3-5-haiku",
    display_name: "Claude 3.5 Haiku",
    description: "Anthropic Claude 3.5 Haiku - 快速响应模型",
    model: "claude-3-5-haiku-20241022",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Google",
    name: "google-gemini-2-0-flash",
    display_name: "Gemini 2.0 Flash",
    description: "Google Gemini 2.0 Flash - 高速多模态模型",
    model: "gemini-2.0-flash",
    api_base: "https://generativelanguage.googleapis.com/v1beta",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Google",
    name: "google-gemini-2-5-pro",
    display_name: "Gemini 2.5 Pro",
    description: "Google Gemini 2.5 Pro - 高智能旗舰模型",
    model: "gemini-2.5-pro-preview-06-05",
    api_base: "https://generativelanguage.googleapis.com/v1beta",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "DeepSeek",
    name: "deepseek-v3",
    display_name: "DeepSeek V3",
    description: "DeepSeek V3 - 国产开源旗舰模型",
    model: "deepseek-chat",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "DeepSeek",
    name: "deepseek-r1",
    display_name: "DeepSeek R1",
    description: "DeepSeek R1 - 推理专用模型",
    model: "deepseek-reasoner",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Zhipu",
    name: "zhipu-glm-4-plus",
    display_name: "智谱 GLM-4 Plus",
    description: "智谱 GLM-4 Plus - 国产旗舰模型",
    model: "glm-4-plus",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Zhipu",
    name: "zhipu-glm-4-long",
    display_name: "智谱 GLM-4 Long",
    description: "智谱 GLM-4 Long - 超长上下文模型",
    model: "glm-4-long",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Alibaba",
    name: "alibaba-qwen-plus",
    display_name: "通义千问 Plus",
    description: "阿里通义千问 Plus - 高性能国产模型",
    model: "qwen-plus",
    api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Alibaba",
    name: "alibaba-qwen-coder-plus",
    display_name: "通义千问 Coder Plus",
    description: "阿里通义千问 Coder Plus - 代码专用模型",
    model: "qwen-coder-plus",
    api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "ByteDance",
    name: "bytedance-doubao-pro",
    display_name: "豆包 Pro",
    description: "字节跳动豆包 Pro - 抖音旗下 AI 模型",
    model: "doubao-pro-32k",
    api_base: "https://ark.cn-beijing.volces.com/api/v3",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "ByteDance",
    name: "bytedance-doubao-thinking",
    display_name: "豆包 思考模型",
    description: "字节跳动豆包 思考模型 - 推理能力增强",
    model: "doubao-thinking",
    api_base: "https://ark.cn-beijing.volces.com/api/v3",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Minimax",
    name: "minimax-abab-6-5s",
    display_name: "MiniMax ABAB 6.5S",
    description: "MiniMax ABAB 6.5S - 海螺 AI 同款模型",
    model: "abab6.5s-chat",
    api_base: "https://api.minimax.chat/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Baichuan",
    name: "baichuan4-turbo",
    display_name: "百川 4 Turbo",
    description: "百川 4 Turbo - 高性能国产模型",
    model: "baichuan4-turbo",
    api_base: "https://api.baichuan-ai.com/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Mistral",
    name: "mistral-large",
    display_name: "Mistral Large",
    description: "Mistral Large - 欧洲领先开源模型",
    model: "mistral-large-latest",
    api_base: "https://api.mistral.ai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Cohere",
    name: "cohere-command-r-plus",
    display_name: "Cohere Command R+",
    description: "Cohere Command R+ - 长上下文推理模型",
    model: "command-r-plus",
    api_base: "https://api.cohere.ai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "01.AI",
    name: "01ai-yi-ultra",
    display_name: "零一迷雾 YI Ultra",
    description: "01.AI YI Ultra - 李开复旗下模型",
    model: "yi-ultra",
    api_base: "https://api.01.ai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
];

export const providers = [...new Set(modelPresets.map((p) => p.provider))];

export function getPresetsByProvider(provider: string): ModelPreset[] {
  return modelPresets.filter((p) => p.provider === provider);
}
