export type ModelPreset = {
  provider: string;
  name: string;
  display_name: string;
  description: string;
  model: string;
  api_base: string;
  supports_vision: boolean;
  supports_thinking: boolean;
  supports_reasoning_effort: boolean;
  use_responses_api: boolean;
  output_version: string | null;
  thinking: Record<string, unknown> | null;
  when_thinking_enabled: Record<string, unknown> | null;
};

export const modelPresets: ModelPreset[] = [
  // ============================================================================
  // OpenAI Models
  // ============================================================================
  {
    provider: "OpenAI",
    name: "openai-gpt-4.1",
    display_name: "GPT-4.1",
    description: "OpenAI GPT-4.1 - 最新旗舰多模态模型",
    model: "gpt-4.1",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-gpt-4.1-mini",
    display_name: "GPT-4.1 Mini",
    description: "OpenAI GPT-4.1 Mini - 高性价比轻量版",
    model: "gpt-4.1-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-gpt-4o",
    display_name: "GPT-4o",
    description: "OpenAI GPT-4o - 多模态旗舰模型，支持视觉和思考",
    model: "gpt-4o",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-gpt-4o-mini",
    display_name: "GPT-4o Mini",
    description: "OpenAI GPT-4o Mini - 高性价比多模态模型",
    model: "gpt-4o-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-o3",
    display_name: "OpenAI o3",
    description: "OpenAI o3 - 旗舰推理模型，200K 上下文",
    model: "o3",
    api_base: "https://api.openai.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-o3-mini",
    display_name: "OpenAI o3-mini",
    description: "OpenAI o3-mini - 轻量推理模型，128K 上下文",
    model: "o3-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-o4-mini",
    display_name: "OpenAI o4-mini",
    description: "OpenAI o4-mini - 高性价比推理模型，支持视觉",
    model: "o4-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "OpenAI",
    name: "openai-o1-mini",
    display_name: "OpenAI o1-mini",
    description: "OpenAI o1-mini - 入门推理模型",
    model: "o1-mini",
    api_base: "https://api.openai.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // Anthropic Claude Models
  // ============================================================================
  {
    provider: "Anthropic",
    name: "anthropic-claude-opus-4.7",
    display_name: "Claude Opus 4.7",
    description: "Anthropic Claude Opus 4.7 - 旗舰模型，1M 上下文",
    model: "claude-opus-4-7-20250514",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: { type: "enabled" },
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "Anthropic",
    name: "anthropic-claude-sonnet-4.6",
    display_name: "Claude Sonnet 4.6",
    description: "Anthropic Claude Sonnet 4.6 - 均衡型，200K 上下文",
    model: "claude-sonnet-4-6-20250514",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: { type: "enabled" },
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "Anthropic",
    name: "anthropic-claude-3-5-sonnet",
    display_name: "Claude 3.5 Sonnet",
    description: "Anthropic Claude 3.5 Sonnet - 智能与速度平衡",
    model: "claude-3-5-sonnet-20241022",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Anthropic",
    name: "anthropic-claude-3-5-haiku",
    display_name: "Claude 3.5 Haiku",
    description: "Anthropic Claude 3.5 Haiku - 快速响应模型",
    model: "claude-3-5-haiku-20241022",
    api_base: "https://api.anthropic.com/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // Google Gemini Models
  // ============================================================================
  {
    provider: "Google",
    name: "google-gemini-2.5-pro",
    display_name: "Gemini 2.5 Pro",
    description: "Google Gemini 2.5 Pro - 高智能旗舰模型，1M 上下文",
    model: "gemini-2.5-pro-preview-06-05",
    api_base: "https://generativelanguage.googleapis.com/v1beta",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Google",
    name: "google-gemini-2.5-flash",
    display_name: "Gemini 2.5 Flash",
    description: "Google Gemini 2.5 Flash - 高性价比多模态模型",
    model: "gemini-2.5-flash-preview-06-05",
    api_base: "https://generativelanguage.googleapis.com/v1beta",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Google",
    name: "google-gemini-2.0-flash",
    display_name: "Gemini 2.0 Flash",
    description: "Google Gemini 2.0 Flash - 高速多模态模型",
    model: "gemini-2.0-flash",
    api_base: "https://generativelanguage.googleapis.com/v1beta",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // DeepSeek Models
  // ============================================================================
  {
    provider: "DeepSeek",
    name: "deepseek-v4-pro",
    display_name: "DeepSeek V4 Pro",
    description: "DeepSeek V4 Pro - 旗舰推理模型，1M 上下文",
    model: "deepseek-v4-pro",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { extra_body: { thinking: { type: "enabled" } } },
  },
  {
    provider: "DeepSeek",
    name: "deepseek-v4-flash",
    display_name: "DeepSeek V4 Flash",
    description: "DeepSeek V4 Flash - 高性价比推理模型",
    model: "deepseek-v4-flash",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { extra_body: { thinking: { type: "enabled" } } },
  },
  {
    provider: "DeepSeek",
    name: "deepseek-r1",
    display_name: "DeepSeek R1",
    description: "DeepSeek R1 - 纯推理模型",
    model: "deepseek-reasoner",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { extra_body: { thinking: { type: "enabled" } } },
  },
  {
    provider: "DeepSeek",
    name: "deepseek-r1-0528",
    display_name: "DeepSeek R1-0528",
    description: "DeepSeek R1-0528 - 特定日期版本推理模型",
    model: "deepseek-reasoner-0528",
    api_base: "https://api.deepseek.com/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: true,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { extra_body: { thinking: { type: "enabled" } } },
  },

  // ============================================================================
  // Groq Models (High-speed LPU inference)
  // ============================================================================
  {
    provider: "Groq",
    name: "groq-llama-4-scout",
    display_name: "Llama 4 Scout (Groq)",
    description: "Groq Llama 4 Scout - MoE 架构，高速推理",
    model: "llama-4-scout",
    api_base: "https://api.groq.com/openai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Groq",
    name: "groq-llama-4-maverick",
    display_name: "Llama 4 Maverick (Groq)",
    description: "Groq Llama 4 Maverick - 高性能推理",
    model: "llama-4-maverick",
    api_base: "https://api.groq.com/openai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Groq",
    name: "groq-llama-3-3-70b",
    display_name: "Llama 3.3 70B (Groq)",
    description: "Groq Llama 3.3 70B - 高性能开源模型",
    model: "llama-3.3-70b-versatile",
    api_base: "https://api.groq.com/openai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Groq",
    name: "groq-qwen3-32b",
    display_name: "Qwen3 32B (Groq)",
    description: "Groq Qwen3 32B - 多语言开源模型",
    model: "qwen-3-32b",
    api_base: "https://api.groq.com/openai/v1",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // xAI Grok Models
  // ============================================================================
  {
    provider: "xAI",
    name: "xai-grok-4.3",
    display_name: "Grok 4.3",
    description: "xAI Grok 4.3 - 旗舰推理模型，131K 上下文",
    model: "grok-4.3",
    api_base: "https://api.x.ai/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "xAI",
    name: "xai-grok-3",
    display_name: "Grok 3",
    description: "xAI Grok 3 - 主力推理模型",
    model: "grok-3",
    api_base: "https://api.x.ai/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // Cohere Command Models
  // ============================================================================
  {
    provider: "Cohere",
    name: "cohere-command-a",
    display_name: "Command A",
    description: "Cohere Command A - 旗舰 RAG 优化模型，256K 上下文",
    model: "command-a-03-2025",
    api_base: "https://api.cohere.ai/v2",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Cohere",
    name: "cohere-command-r-plus",
    display_name: "Command R+",
    description: "Cohere Command R+ - 高端 RAG 模型，128K 上下文",
    model: "command-r-plus-08-2024",
    api_base: "https://api.cohere.ai/v2",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Cohere",
    name: "cohere-command-r7b",
    display_name: "Command R7B",
    description: "Cohere Command R7B - 高效 RAG 模型，128K 上下文",
    model: "command-r7b-12-2024",
    api_base: "https://api.cohere.ai/v2",
    supports_vision: false,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // GLM / 智谱 AI Models
  // ============================================================================
  {
    provider: "GLM",
    name: "glm-5.1",
    display_name: "GLM-5.1 智谱旗舰",
    description: "智谱 GLM-5.1 - 旗舰模型，SOTA on SWE-Bench Pro",
    model: "glm-5.1",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "GLM",
    name: "glm-5",
    display_name: "GLM-5 智谱高级",
    description: "智谱 GLM-5 - 高智能模型，对标 Claude Opus 4.5",
    model: "glm-5",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "GLM",
    name: "glm-4.7",
    display_name: "GLM-4.7 智谱主流",
    description: "智谱 GLM-4.7 - 主流推荐，Code Arena #1",
    model: "glm-4.7",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "GLM",
    name: "glm-4.7-flashx",
    display_name: "GLM-4.7 FlashX 智谱高速",
    description: "智谱 GLM-4.7 FlashX - 轻量高速，中文写作/翻译",
    model: "glm-4.7-flashx",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "GLM",
    name: "glm-5v-turbo",
    display_name: "GLM-5V-Turbo 智谱多模态",
    description: "智谱 GLM-5V-Turbo - 旗舰多模态，代码截图还原",
    model: "glm-5v-turbo",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },
  {
    provider: "GLM",
    name: "glm-4.6v",
    display_name: "GLM-4.6V 智谱视觉",
    description: "智谱 GLM-4.6V - 视觉推理，原生 Function Call",
    model: "glm-4.6v",
    api_base: "https://open.bigmodel.cn/api/paas/v4",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: { thinking: { type: "enabled" } },
  },

  // ============================================================================
  // MiniMax Models
  // ============================================================================
  {
    provider: "Minimax",
    name: "minimax-m2.7",
    display_name: "MiniMax M2.7",
    description: "MiniMax M2.7 - 旗舰文本模型，1M 上下文",
    model: "MiniMax-M2.7",
    api_base: "https://api.minimax.io/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Minimax",
    name: "minimax-m2.7-highspeed",
    display_name: "MiniMax M2.7 Highspeed",
    description: "MiniMax M2.7 Highspeed - 高速版",
    model: "MiniMax-M2.7-highspeed",
    api_base: "https://api.minimax.io/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Minimax",
    name: "minimax-m2.5",
    display_name: "MiniMax M2.5",
    description: "MiniMax M2.5 - 中端模型",
    model: "MiniMax-M2.5",
    api_base: "https://api.minimax.io/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Minimax",
    name: "minimax-m2.5-lightning",
    display_name: "MiniMax M2.5 Lightning",
    description: "MiniMax M2.5 Lightning - 极速版",
    model: "MiniMax-M2.5-lightning",
    api_base: "https://api.minimax.io/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },

  // ============================================================================
  // Qwen / 阿里巴巴 Models
  // ============================================================================
  {
    provider: "Qwen",
    name: "qwen3-max",
    display_name: "Qwen3-Max 通义旗舰",
    description: "阿里 Qwen3-Max - 旗舰模型，对标 GPT-4.5",
    model: "qwen3-max",
    api_base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Qwen",
    name: "qwen3.5-plus",
    display_name: "Qwen3.5-Plus 通义高端",
    description: "阿里 Qwen3.5-Plus - 高端模型",
    model: "qwen3.5-plus",
    api_base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Qwen",
    name: "qwen3.5-flash",
    display_name: "Qwen3.5-Flash 通义高性价",
    description: "阿里 Qwen3.5-Flash - 高性价比",
    model: "qwen3.5-flash",
    api_base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    supports_vision: false,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Qwen",
    name: "qwen-vl-max",
    display_name: "Qwen-VL-Max 通义视觉旗舰",
    description: "阿里 Qwen-VL-Max - 旗舰视觉模型",
    model: "qwen-vl-max",
    api_base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    supports_vision: true,
    supports_thinking: false,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
  {
    provider: "Qwen",
    name: "qvq-max",
    display_name: "QVQ-Max 通义视觉推理",
    description: "阿里 QVQ-Max - 视觉推理模型",
    model: "qvq-max",
    api_base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    supports_vision: true,
    supports_thinking: true,
    supports_reasoning_effort: false,
    use_responses_api: false,
    output_version: null,
    thinking: null,
    when_thinking_enabled: null,
  },
];

export const providers = [...new Set(modelPresets.map((p) => p.provider))];

export function getPresetsByProvider(provider: string): ModelPreset[] {
  return modelPresets.filter((p) => p.provider === provider);
}
